services:
  fastapi-cont:
    image: postgres
    container_name: fastapi-cont
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD} 
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - fastapi_data:/var/lib/postgresql/data

volumes:
  fastapi_data: